// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Helper to create chainable mock methods that are thenable
const createChainable = (): Record<string, unknown> => {
  const chain: Record<string, (...args: unknown[]) => typeof chain> & { then?: (resolve: (value: { data: null; error: null }) => void, reject?: (error: unknown) => void) => Promise<void | { data: null; error: null }> } = {};
  const methods = ['select', 'insert', 'update', 'upsert', 'delete', 'eq', 'neq', 'gt', 'gte', 'lt', 'lte', 'like', 'ilike', 'is', 'in', 'contains', 'containedBy', 'range', 'overlaps', 'textSearch', 'match', 'not', 'or', 'filter', 'order', 'limit', 'single', 'maybeSingle', 'csv', 'explain'];
  methods.forEach(method => {
    chain[method] = (..._args: unknown[]) => chain;
  });
  // Make it thenable so await works
  chain.then = (resolve: (value: { data: null; error: null }) => void) => {
    return Promise.resolve({ data: null, error: null }).then(resolve);
  };
  return chain;
};

// Check if the key looks like a valid Supabase anon key (JWT format)
const isValidSupabaseKey = (key: string): boolean => {
  return key.startsWith('eyJ') && key.length > 100;
};

// Create a mock client that returns empty data if Supabase is not configured
const createSupabaseClient = (): SupabaseClient<Database> => {
  const isMisconfigured = !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY || !isValidSupabaseKey(SUPABASE_PUBLISHABLE_KEY);
  
  if (isMisconfigured) {
    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      console.warn('[Supabase] Missing environment variables. Auth features will be disabled.');
    } else if (!isValidSupabaseKey(SUPABASE_PUBLISHABLE_KEY)) {
      console.warn('[Supabase] Invalid API key format. The key should be a JWT token starting with "eyJ". Please check your VITE_SUPABASE_PUBLISHABLE_KEY.');
    }
    
    const authError = { message: 'Supabase is not configured. Please add a valid VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (anon public key from Supabase dashboard).' };
    
    // Return a mock client that doesn't throw errors
    return {
      auth: {
        getSession: async () => ({ data: { session: null }, error: null }),
        getUser: async () => ({ data: { user: null }, error: null }),
        onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
        signOut: async () => ({ error: null }),
        signInWithOAuth: async () => ({ data: { provider: '', url: '' }, error: authError }),
        signInWithPassword: async () => ({ data: { user: null, session: null }, error: authError }),
        signUp: async () => ({ data: { user: null, session: null }, error: authError }),
      },
      from: () => createChainable(),
    } as unknown as SupabaseClient<Database>;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
};

export const supabase = createSupabaseClient();
